map_server:
  ros__parameters:
    yaml_filename: "/home/ramzy/delivery_robot/src/Autonomous_System_nav2/slam/robot_slam/maps/map_1739376647.yaml"
    topic_name: "map"
    frame_id: "map"

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65


